_wandb:
    value:
        cli_version: 0.23.1
        e:
            rs18peszrms6zo0ezyipihpwpm1w1lv7:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                args:
                    - --model
                    - efficientnet_b0
                    - --epochs
                    - "5"
                    - --wandb
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "132507553792"
                email: stephpark1plus1@gmail.com
                executable: /Users/stephpark/Documents/xai-proj-m-ws2526/venv/bin/python
                git:
                    commit: 39f729fdcd1bc54545f93eec4680ab8e5b5e3251
                    remote: git@github.com:stu-rdy/xai-proj-m-ws2526.git
                host: P.local
                memory:
                    total: "8589934592"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/stephpark/Documents/xai-proj-m-ws2526/scripts/train.py
                python: CPython 3.9.6
                root: /Users/stephpark/Documents/xai-proj-m-ws2526
                startedAt: "2025-12-14T13:01:54.158533Z"
                writerId: rs18peszrms6zo0ezyipihpwpm1w1lv7
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 16
                - 62
            "4": 3.9.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
architecture:
    value: efficientnet_b0
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
momentum:
    value: 0.9
num_classes:
    value: 10
weight_decay:
    value: 0.0001
